const productCategory = [
  { id: 1, label: 'Tops', value: 'tops' },
  { id: 2, label: 'Hoodies & Sweatshirts', value: 'hoodies_sweatshirts' },
  { id: 3, label: 'Outerwear', value: 'outerwear' },
  { id: 4, label: 'Bottoms', value: 'bottoms' },
  { id: 5, label: 'Sets', value: 'sets' },
  { id: 6, label: 'Activewear', value: 'activewear' },
  { id: 7, label: 'Graphic Tees', value: 'graphic_tees' },
  { id: 8, label: 'Oversized Fits', value: 'oversized_fits' },
  { id: 9, label: 'Cargos & Utility Wear', value: 'cargos_utility_wear' },
  { id: 10, label: 'Essential Basics', value: 'essential_basics' },
  { id: 11, label: 'Limited Drops / Exclusive', value: 'limited_drops_exclusive' },
  { id: 12, label: 'Vintage / Washed Collection', value: 'vintage_washed_collection' },
  { id: 13, label: 'Caps & Beanies', value: 'caps_beanies' },
  { id: 14, label: 'Bags', value: 'bags' },
  { id: 15, label: 'Socks', value: 'socks' },
  { id: 16, label: 'Jewelry', value: 'jewelry' },
  { id: 17, label: 'Belts', value: 'belts' },
  { id: 18, label: 'Summer Collection', value: 'summer_collection' },
  { id: 19, label: 'Winter Collection', value: 'winter_collection' },
  { id: 20, label: 'Drop 001 / Drop 002', value: 'drop_series' },
  { id: 21, label: 'Collabs', value: 'collabs' },
  { id: 22, label: 'Men', value: 'men' },
  { id: 23, label: 'Women', value: 'women' },
  { id: 24, label: 'Unisex', value: 'unisex' },
  { id: 25, label: 'Smartphones', value: 'smartphones' },
  { id: 26, label: 'Tablets & iPads', value: 'tablets_ipads' },
  { id: 27, label: 'Laptops', value: 'laptops' },
  { id: 28, label: 'Smartwatches & Wearables', value: 'smartwatches_wearables' },
  { id: 29, label: 'Gaming', value: 'gaming' },
  { id: 30, label: 'Chargers & Adapters', value: 'chargers_adapters' },
  { id: 31, label: 'Power Banks', value: 'power_banks' },
  { id: 32, label: 'Phone Cases & Screen Protectors', value: 'phone_cases_screen_protectors' },
  { id: 33, label: 'Earphones & Headphones', value: 'earphones_headphones' },
  { id: 34, label: 'Cables', value: 'cables' },
  { id: 35, label: 'Smart Home Devices', value: 'smart_home_devices' },
  { id: 36, label: 'Bluetooth Devices', value: 'bluetooth_devices' },
  { id: 37, label: 'Streaming Devices', value: 'streaming_devices' },
  { id: 38, label: 'Keyboards & Mouse', value: 'keyboards_mouse' },
  { id: 39, label: 'Storage Devices', value: 'storage_devices' },
  { id: 40, label: 'Routers & Networking', value: 'routers_networking' },
  { id: 41, label: 'Car Accessories', value: 'car_accessories' },
  { id: 42, label: 'Fitness Gadgets', value: 'fitness_gadgets' },
  { id: 43, label: 'Portable Fans / Mini Gadgets', value: 'portable_fans_mini_gadgets' },
  { id: 44, label: 'LED Lights / Room Setup', value: 'led_lights_room_setup' },
  { id: 45, label: 'New Arrivals', value: 'new_arrivals' },
  { id: 46, label: 'Best Sellers', value: 'best_sellers' },
  { id: 47, label: 'Hot Deals / Discounts', value: 'hot_deals_discounts' },
  { id: 48, label: 'Budget Picks', value: 'budget_picks' },
  { id: 49, label: 'Premium Devices', value: 'premium_devices' },
];

export default productCategory;
